* Encoding: UTF-8.

CROSSTABS
  /TABLES=JSR_02 BY WLY_145
  /FORMAT=AVALUE TABLES
  /STATISTICS=ETA GAMMA 
  /CELLS=COUNT
  /COUNT ROUND CELL.

ONEWAY WLY_145 BY JSR_02
  /MISSING ANALYSIS.

ONEWAY WLY_145 BY JSR_02
  /STATISTICS DESCRIPTIVES 
  /MISSING ANALYSIS.