* Encoding: UTF-8.

CROSSTABS
  /TABLES=JSR_02 BY SFC_07
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT ROW COLUMN 
  /COUNT ROUND CELL.

NONPAR CORR
  /VARIABLES=JSR_02 SFC_07
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

ONEWAY WLY_145 BY JSR_02
  /STATISTICS DESCRIPTIVES 
  /MISSING ANALYSIS.
