* Encoding: UTF-8.

CROSSTABS
  /TABLES=SFC_07 BY WLY_145
  /FORMAT=AVALUE TABLES
  /STATISTICS=ETA GAMMA 
  /CELLS=COUNT
  /COUNT ROUND CELL.

ONEWAY WLY_145 BY SFC_07
  /MISSING ANALYSIS.
