
FREQUENCIES VARIABLES=WLY_145
  /FORMAT=NOTABLE
  /NTILES=4
  /STATISTICS=STDDEV VARIANCE RANGE MEAN MEDIAN MODE
  /ORDER=ANALYSIS.

FREQUENCIES VARIABLES=JSR_02
  /FORMAT=NOTABLE
  /NTILES=4
  /STATISTICS=MEDIAN MODE RANGE 
  /ORDER=ANALYSIS.

FREQUENCIES VARIABLES=SFC_07
  /FORMAT=NOTABLE
  /NTILES=4
  /STATISTICS=MEDIAN MODE RANGE 
  /ORDER=ANALYSIS.

